### ISSUE TITLE
API auth no longer working

### ISSUE THREAD

**Issue by ravensergio** [lpandolfini/node-red-contrib-hass#5]
Hi. I don't know if someone is still managing this, but the LEGACY API PASSWORD seems to be dropped for the latest Home Assistant. So, sadly, by using this node, Home assistant keeps banning my HASSio ip. The latest auth long lived tokens, or something else is needed to connect to the server. I really liked this node, since it sent all kinds of attributes back to my Home Assistant.

**Comment by lpandolfini** [comment]
Hello,
I updated the code to use the long-lived access token as stated in the new API documentation.
Tested with version 0.104.3.
Your feedback is welcome!
Thanks
Luca
